/**
 * @module server/routes/bliss
 */

const path = require('path');
const express = require('express');
const router = express.Router();
const designerMiddleware = require('../designer-middleware.js')
const env = require('../env.js');

/**
 * Route for designer iframe.
 *
 * @name Designer Iframe
 * @route {GET} /bliss/designer/:token/:workspace/*
 * @routeparam {string} token - secure token generated by server
 * @routeparam {string} workspace - workspace name
 */
router.use('/designer/:token/:workspace/*', designerMiddleware);

/**
 * @name BlissTree component
 * @route {GET} /bliss/designer/bliss-tree
 */
router.use('/designer/bliss-tree',
  express.static(path.join(env.app, 'bliss-tree')));

/**
 * @name BlissProperties component
 * @route {GET} /bliss/designer/bliss-properties
 */
router.use('/designer/bliss-properties',
  express.static(path.join(env.app, 'bliss-properties')));

/**
 * @name BlissJavascript component
 * @route {GET} /bliss/designer/bliss-javascript
 */
router.use('/designer/bliss-javascript',
  express.static(path.join(env.app, 'bliss-javascript')));

/**
 * @name BlissUtils component
 * @route {GET} /bliss/designer/bliss-utils
 */
router.use('/designer/bliss-utils',
  express.static(path.join(env.app, 'bliss-utils')));

/**
 * Route for BlissProperties component
 *
 * @name node_modules
 * @route {GET} /bliss/node_modules
 */
router.use('/node_modules',
  express.static(env.node_modules));

/**
 * Route for Bliss UI Editor
 *
 * @name BlissEditor
 * @route {GET} /bliss
 */
router.use('/', express.static(env.app));

console.log(env.app)

module.exports = router
